(defcaixa
  :name
  "lava-aws"
  :kind
  :Biblioteca
  :ecosystem
  :rust-single-crate
  :package
  {:name "lava-aws"
   :version "0.1.0"
   :description "Tatara-lisp typed surface for AWS resources. Auto-generated by lava-forge from terraform-provider-aws schema; sits on lava-core. Tatara equivalent of pangea-aws."
   :license "MIT"
   :repository "https://github.com/pleme-io/lava-aws"}
  :ci-config
  {:bump {:default-type "patch"}
   :publish {:no-verify true}}
  :workflows
  [:auto-release :pre-merge-gate :security-gate])
