# nix/modules/nixos.nix — auto-generated from lava-aws.caixa.lisp
# description: "Tatara-lisp typed surface for AWS resources. Auto-generated by lava-forge from terraform-provider-aws schema; sits on lava-core. Tatara equivalent of pangea-aws."
{ config, lib, pkgs, ... }:
let
  cfg = config.services.lava-aws;
in {
  options.services.lava-aws = {
    enable = lib.mkEnableOption "lava-aws";
    package = lib.mkOption {
      type = lib.types.package;
      default = pkgs.lava-aws or null;
    };
  };
  config = lib.mkIf cfg.enable {
    environment.systemPackages = [ cfg.package ];
  };
}
